apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
      - name: kafka-consumer
        image: binod1243/kafka:consumer
        imagePullPolicy: Always
        env:
        - name: KAFKA_BROKER
          value: "kafka-broker-headless.kafka.svc.cluster.local:9092
        - name: TOPIC_NAME
          value: "test-topic"
        - name: LOG_LEVEL  # Set environment variable for logging level
          value: "INFO"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-consumer-service
spec:
  selector:
    app: kafka-consumer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
