apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
      - name: kafka-producer
        image: binod1243/kafka:producer
        imagePullPolicy: Always
        env:
        - name: KAFKA_BROKER
          value: "kafka-broker-headless.kafka.svc.cluster.local:9092"
        - name: TOPIC_NAME
          value: "test-topic"
        - name: LOG_LEVEL  # Set environment variable for logging level
          value: "INFO"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-producer-service
spec:
  selector:
    app: kafka-producer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
