name: Build and Push Producer Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Print Current Directory
      run: pwd

    - name: List Contents of Current Directory
      run: ls -la
    - name: List Contents of Producer Directory
      run: ls -la ./producer

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: ./producer
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/kafka:producer
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: ./consumer
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/kafka:consumer